openapi:
  title: api_projeto_final API
  version: 1.0.0
  description: API gerada automaticamente pelo Vaden.
  enable: true

#redis:
#  port: 6379
#  host: localhost
server:
  port: 8080
  host: localhost

env:
  base_url: http://localhost
  mode: debug
