openapi:
  title: api_projeto_final API
  version: 1.0.0
  description: API gerada automaticamente pelo Vaden.
  enable: true

mysql:
  hostname: mysql.grod.ovh
  username: innovacad_tpsi0525
  database: innovacad_tpsi0525
  password: H>u:b]0M#-+7U,.%wd1knx1-e

redis:
  port: 6379
  host: redis.grod.ovh

server:
  port: 8080
  host: localhost
  cors:
    enabled: true
    allowed-origins: "*"

security:
  secret: aV9sb3ZlX2lubm92YWNhZF9vX3BlZHJvX25hb19lX3NhbnRvX2Vfb19maWxpcGVfZV9hbmFv
  tokenValidity: 900
  refreshTokenValidity: 3600
  issuer: "innovacad_tpsi0525"
  audiences:
    - "innovacad_tpsi0525"

env:
  base_url: http://localhost
  mode: debug

auth:
  protocol: "http"
  host: "localhost"
  port: 10000
