name: innovacad_api
description: API em Dart para o Projeto Final na Atec, Turma TPSI 0525..
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

dependencies:
  dio: ^5.9.0
  redis: ^4.0.0
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.2
  vaden_security: ^1.0.0
  vaden: ^1.0.2

dev_dependencies:
  build_runner: ^2.10.3
  vaden_class_scanner: ^1.0.2