name: innovacad_api
description: API em Dart para o Projeto Final na Atec, Turma TPSI 0525..
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

dependencies:
  dio: ^5.9.0
  redis: ^4.0.0
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.2
  vaden_security: ^1.0.0
  vaden: ^1.0.2
  result_dart: ^2.1.1
  uuid: ^4.5.2
  mysql_utils: ^2.1.12
  jose: ^0.3.5
  mysql_client_plus: ^0.1.2
  json_annotation: ^4.9.0
  dart_jsonwebtoken: ^3.3.1
  mailer: ^6.6.0
  dotenv: ^4.2.0
  shelf_multipart: ^2.0.1
  shelf_static: ^1.1.3

dev_dependencies:
  build_runner: ^2.10.3
  json_serializable: ^6.11.2
  vaden_class_scanner: ^1.0.2
